[project]
# Project metadata. Available keys are documented at:
# https://packaging.python.org/en/latest/specifications/declaring-project-metadata
name = "GenCFD"
description = "Machine learning for Computational Fluid Dynamics."
readme = "README.md"
requires-python = ">=3.7" 
license = {file = "LICENSE"}
authors = [
  {name = "camlab-ethz", email="yramic@ethz.ch"},
]
classifiers = [  # List of https://pypi.org/classifiers/
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3 :: Only",
    "License :: OSI Approved :: Apache Software License",
    "Intended Audience :: Science/Research",
]
keywords = [
  "dynamical systems", "machine learning", "PyTorch"
]
dependencies = [
    "absl-py>=2.1.0",
    "certifi>=2024.8.30",
    "cftime>=1.6.4",
    "charset-normalizer>=3.4.0",
    "contourpy>=1.3.0",
    "cycler>=0.12.1",
    "einops>=0.6.1",
    "filelock>=3.16.0",
    "fonttools>=4.54.1",
    "fsspec>=2024.9.0",
    "GPUtil>=1.4.0",
    "grpcio>=1.66.1",
    "idna>=3.10",
    "Jinja2>=3.1.4",
    "kiwisolver>=1.4.7",
    "lightning-utilities>=0.11.7",
    "Markdown>=3.7",
    "MarkupSafe>=2.1.5",
    "matplotlib>=3.9.2",
    "mpmath>=1.3.0",
    "netCDF4>=1.7.1.post2",
    "networkx>=3.3",
    "numpy>=2.1.1",
    "nvidia-cublas-cu12>=12.1.3.1",
    "nvidia-cuda-cupti-cu12>=12.1.105",
    "nvidia-cuda-nvrtc-cu12>=12.1.105",
    "nvidia-cuda-runtime-cu12>=12.1.105",
    "nvidia-cudnn-cu12>=9.1.0.70",
    "nvidia-cufft-cu12>=11.0.2.54",
    "nvidia-curand-cu12>=10.3.2.106",
    "nvidia-cusolver-cu12>=11.4.5.107",
    "nvidia-cusparse-cu12>=12.1.0.106",
    "nvidia-nccl-cu12>=2.20.5",
    "nvidia-nvjitlink-cu12>=12.6.68",
    "nvidia-nvtx-cu12>=12.1.105",
    "packaging>=24.1",
    "pandas>=2.2.3",
    "pillow>=10.4.0",
    "platformdirs>=4.3.6",
    "pooch>=1.8.2",
    "protobuf>=5.28.2",
    "pyparsing>=3.1.4",
    "python-dateutil>=2.9.0.post0",
    "pytz>=2024.2",
    "pyvista>=0.44.1",
    "requests>=2.32.3",
    "scipy>=1.15.1",
    "scooby>=0.10.0",
    "six>=1.16.0",
    "sympy>=1.13.2",
    "tensorboard>=2.18.0",
    "tensorboard-data-server>=0.7.2",
    "torch>=2.4.1",
    "torch-tb-profiler>=0.4.3",
    "torchmetrics>=1.4.2",
    "torchvision>=0.19.1",
    "tqdm>=4.66.5",
    "triton>=3.0.0",
    "typing_extensions>=4.12.2",
    "tzdata>=2024.2",
    "urllib3>=2.2.3",
    "vtk>=9.3.1",
    "Werkzeug>=3.0.4",
]

# `version` is automatically set by flit to use `swirl_dynamics.__version__`
dynamic = ["version"]

[project.urls]
homepage = "https://github.com/camlab-ethz/GenCFD"
repository = "https://github.com/camlab-ethz/GenCFD"

[build-system]
# Build system specify which backend is used to build/install the project (flit,
# poetry, setuptools,...). All backends are supported by `pip install`
requires = ["flit_core >=3.8,<4"]
build-backend = "flit_core.buildapi"